name: Changelog Log

on:
    push:
        branches: [main]
        paths:
            - "**/CHANGELOG*.md"
            - "**/changelog*.md"

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Send changelog to webhook
              uses: ./
              with:
                  webhook_url: ${{ secrets.CHANGELOG_WEBHOOK_URL }}
                  webhook_headers_json: '{"Content-Type":"application/json","X-DX-Logs-Key":"${{ secrets.CHANGELOG_SECRET }}"}'
                  extra_body_json: '{"route":"community","destination":"changelog-slack"}'
                  # Optional overrides:
                  # file_globs: "CHANGELOG.md,**/CHANGELOG*.md"
                  # entry_separator_regex: "^##\\s+.*$"
                  # http_method: "POST"
                  # webhook_headers_json: '{"X-Api-Key":"..."}'
                  # include_body_raw: "false"
