name: Release and Publish

on:
    push:
        branches: [main]

jobs:
    release-please:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
        steps:
            - name: Release Please
              id: release
              uses: google-github-actions/release-please-action@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  config-file: .github/release-please-config.json
                  manifest-file: .github/.release-please-manifest.json

    publish:
        needs: release-please
        if: needs.release-please.outputs.release_created
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"
                  cache: "pnpm"

            - name: Install dependencies
              shell: bash
              run: |
                  pnpm install --prod --no-frozen-lockfile

            - name: Publish package
              shell: bash
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  pnpm publish --access public --no-git-checks
