name: release-please

on:
    push:
        branches: [main]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Release Please
              uses: google-github-actions/release-please-action@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  command: manifest
